### ISSUE TITLE
[Idea]: Support Alpine UI components with Structeezy

### ISSUE THREAD

**Issue by briansteeleca** [thewebforge/structeezy-docs#32]
### Contact Details

steeleware@gmail.com

### What would this feature do?

The ability to parse & inject [Alpine UI components](https://alpinejs.dev/components) with Structeezy. Currently, Accordion works, but most of the others don't. I suspect it may be due to the chained attributes eg. x-on:keydown.right.prevent.stop

### What would be this feature settings?

No settings necessary, however, if something fails parsing & injecting, it would be nice if it showed you where it was failing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cbontems** [comment]
Hello @briansteeleca ,

This is actually in progress! And you are right, the alpine attributes syntax requires some trick to be parsed properly.

No ETA as I am focusing on oxyprops for now.

**Comment by briansteeleca** [comment]
That's great, glad to hear Cédric, I'm not in a hurry! I'm glad to hear you're working on OxyProps too.

**Comment by cbontems** [comment]
Hi @briansteeleca,

I have parsing Alpinejs attributes working and preparing it for next release.

There is a limitation anyway: if we use the `@` shorthand in place of `x-on:`, like in `@click` in place of `x-on:click`, we get an error in the editor, and then Bricks is stuck, unable to render anything on the page. It works well on frontend, but back-end editor is unusable. This is because for javascript, an attribute name including `@` is invalid. There is no way around because in the editor, the only way to dynamically add attributes to elements is through javascript.

So I have two options:
- Support Aplinejs without the shorthand syntax.
- Try to "intercept" `@` shorthands and swap it for the `x-on:` syntax before injecting the parsed structure in Bricks.

Maybe I can start with option 1 and develop option 2 for a following update.

**Comment by briansteeleca** [comment]
That's great @cbontems ! I've heard about the `@` shorthand issue before. I think as long as users know about it, it's easy enough for them to do a search and replace before pasting into Structeezy. Looking forward to this release!

**Comment by cbontems** [comment]
@briansteeleca I have managed the `@` shorthand.
I have included the core library and the various plugins as structures for easy imports.
I am working an a few basic elements as a starter kit, and will include some examples fro the Alpine Get Started documentation, then it should be ready for release.

Obviously I won't include Alpine UI components, but users with a valid license should be able to copy / parse the source code.

**Comment by briansteeleca** [comment]
Even better! 👍

**Comment by cbontems** [comment]
Any idea about simple examples that would be useful, besides the obvious increment / decrement counter ?

**Comment by cbontems** [comment]
@briansteeleca v1.7 is published with official support for Alpine.js

**Comment by briansteeleca** [comment]
Thanks so much, @cbontems, this is great! I was able to parse all of the official Alpine UI components without any issues.

I'm trying them with Yabe Siul (Tailwind) with only a couple issues. Notifications and Tooltips aren't displaying interactively, but I'll test some more to see what's going on. So far everything else seems to work great.

I'll see what I can do with stripping out the Tailwind classes and styling with BricksProps instead.

It's so nice to have these fully accessible components available in Bricks!
