### ISSUE TITLE
[Improvement]: Restore clipboard after insertion

### ISSUE THREAD

**Issue by jrmyfranck** [thewebforge/structeezy-docs#6]
### Contact Details

hello@jrmyfranck.com

### What would this feature do?

I understand Structeezy is using the clipboard to paste the elements and structures in the page…

But currently it effectively erases what was previously in the clipboard, making it a bit cumbersome to, for example, copy some text from an existing element, inserting a structure, and pasting that text inside — instead, it will paste the text that corresponds to the structure elements. 

In a broader sense, it would be best if we could use Structeezy without being wary of it erasing an info copied to the clipboard which may then be lost forever.

### What would be this feature settings?

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cbontems** [comment]
Hello @jrmyfranck,

Structeezy is using clipboard because this is Bricks way to handle copy/paste in the structure tree. I have no choice but to comply with it unfortunately. My personal preference would be using local storage, like for example Oxygen builder does.

But I understand your frustration, I have the same.

I probably can modify the logic in the following way:

1. copy whatever is in the clipboard to a temporary memory buffer.
2. perform the structure insertion actions.
3. restore clipboard from temporary buffer.

Would this solve the problem in your opinion?

**Comment by jrmyfranck** [comment]
> Would this solve the problem in your opinion?

Yes, absolutely! That's exactly what I had in mind.

**Comment by cbontems** [comment]
This is solved and included in next release.

**Comment by jrmyfranck** [comment]
Sounds great! (This will make a big difference in terms of QoL)

➡️ Should I go ahead and close the issue, or will you take care of that once it's released? (This also applies to other bug reports I’ve opened)

**Comment by cbontems** [comment]
I would like to wait for a few time before closing, to make sure it works for people, not just me and my testing environments.

**Comment by jrmyfranck** [comment]
Sounds great.

**Comment by jrmyfranck** [comment]
Hey @cbontems, haven't had the chance to thoroughly test it yet (been busy with non-Bricks related projects). I‘ll try to get to it during the weekend, and will report back.
